spring:
  application:
    name: lynn-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/LinZhaoguan/spring-cloud-config
          username: 17186784453@163.com
          password: lzg19940210
server:
  port: 1201
eureka:
  client:
    service-url:
     defaultZone: http://localhost:1001/eureka/